// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// ╔═══════════════════════════════════════════════════════════════════╗
// ║  IMPORTANT — RUN THE FOLLOWING COMMAND TO GENERATE THIS FILE:    ║
// ║                                                                   ║
// ║    flutterfire configure                                          ║
// ║                                                                   ║
// ║  This file will be auto-generated with your Firebase project's   ║
// ║  configuration. The values below are PLACEHOLDERS.               ║
// ║                                                                   ║
// ║  Firebase API keys are PUBLIC identifiers, NOT secrets.           ║
// ║  Security is enforced via Firebase Auth + Firestore Rules.        ║
// ╚═══════════════════════════════════════════════════════════════════╝

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'run flutterfire configure to fix this.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'run flutterfire configure to fix this.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run flutterfire configure to fix this.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ──────────────────────────────────────────────
  // PLACEHOLDER VALUES — Replace after running:
  //   flutterfire configure
  // ──────────────────────────────────────────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtovsqTF2p_Hoo8t8olpZwYTl4jxO1p5o',
    appId: '1:1006338958836:web:38ef6f065344339c30c5a1',
    messagingSenderId: '1006338958836',
    projectId: 'task-manager-a758d',
    authDomain: 'task-manager-a758d.firebaseapp.com',
    storageBucket: 'task-manager-a758d.firebasestorage.app',
    measurementId: 'G-JWDQ7345DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA82iP5ZEVzb4QRqhNNZfOfUWAOxlfbO6c',
    appId: '1:1006338958836:android:cb4f0bd7952289cc30c5a1',
    messagingSenderId: '1006338958836',
    projectId: 'task-manager-a758d',
    storageBucket: 'task-manager-a758d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIeUwfj1VMUjbtyhmeKpDsVOouTfT6u0E',
    appId: '1:1006338958836:ios:de7f83c40a381e1430c5a1',
    messagingSenderId: '1006338958836',
    projectId: 'task-manager-a758d',
    storageBucket: 'task-manager-a758d.firebasestorage.app',
    iosClientId: '1006338958836-jivo74os1gudbkbt9c688f82sp9j56c1.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

}